version: 2
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://github.com/Jmainguy/wp-spam
  description: "A golang program to prevent spam from wordpress forms"
  maintainer: Jonathan Seth Mainguy <jon@soh.re>
  license: GPL-2.0
  vendor: Jmainguy
  release: 1
  overrides:
      rpm:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{.Release}}.{{ .Arch }}"
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}-{{.Release}}_{{ .Arch }}"
  formats:
  - deb
  - rpm

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dockers:
  # You can have multiple Docker images.
  -
    id: arm64
    goos: linux
    goarch: arm64

    # Templates of the Docker image names.
    #
    # Templates: allowed.
    image_templates:
      - "zot.soh.re/{{ .ProjectName }}:latest"
      - "zot.soh.re/{{ .ProjectName }}:{{ .Tag }}"

    extra_files:
      - go.mod
      - go.sum

    # Docker build flags.
    #
    # Templates: allowed.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
  -
    id: amd64
    goos: linux
    goarch: amd64

    # Templates of the Docker image names.
    #
    # Templates: allowed.
    image_templates:
      - "zot.soh.re/{{ .ProjectName }}:latest"
      - "zot.soh.re/{{ .ProjectName }}:{{ .Tag }}"

    extra_files:
      - go.mod
      - go.sum

    # Docker build flags.
    #
    # Templates: allowed.
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
