# Base image to use if not specified for individual packages
defaultBaseImage: cgr.dev/chainguard/static:latest

# Default platforms to build for when not specified explicitly
defaultPlatforms:
  - linux/amd64
  - linux/arm64

# SBOM settings, specifying format and location
sbom: spdx
sbomDir: "./sbom"

# Trimpath setting to enable reproducible builds by default
trimpath: false

# Annotations for the OCI image manifest
annotations:
  - org.opencontainers.image.created: "{{.Date}}"
  - org.opencontainers.image.title: "{{.ProjectName}}"
  - org.opencontainers.image.revision: "{{.FullCommit}}"
  - org.opencontainers.image.version: "{{.Version}}"
  - org.opencontainers.image.authors: "Jonathan Seth Mainguy <jon@soh.re>"
  - org.opencontainers.image.vendor: Jmainguy

builds:
  - id: build
    platforms:
      - linux/amd64
      - inux/arm64
